// app actions
export const SET_CONFIG = 'SET_CONFIG';
export const SHOW_FULL_MODAL = 'SHOW_FULL_MODAL';
export const HIDE_FULL_MODAL = 'HIDE_FULL_MODAL';
export const SHOW_PARTIAL_MODAL = 'SHOW_PARTIAL_MODAL';
export const HIDE_PARTIAL_MODAL = 'HIDE_PARTIAL_MODAL';
export const UPDATE_BLUETOOTH_STATE = 'UPDATE_BLUETOOTH_STATE';
export const SET_TITLE_BAR = 'SET_TITLE_BAR';

// auth actions
export const LOGIN = 'LOGIN';
export const LOGIN__START = 'LOGIN__START';
export const LOGIN__ERROR = 'LOGIN__ERROR';
export const SIGNUP = 'SIGNUP';
export const SIGNUP__START = 'SIGNUP__START';
export const SIGNUP__ERROR = 'SIGNUP__ERROR';
export const PASSWORD_RESET = 'PASSWORD_RESET';
export const PASSWORD_RESET__START = 'PASSWORD_RESET__START';
export const PASSWORD_RESET__ERROR = 'PASSWORD_RESET__ERROR';
export const SIGN_OUT = 'SIGN_OUT';
export const SIGN_OUT__START = 'SIGN_OUT__START';
export const SIGN_OUT__ERROR = 'SIGN_OUT__ERROR';
export const SET_ACCESS_TOKEN = 'SET_ACCESS_TOKEN';
export const SET_ACCESS_TOKEN__START = 'SET_ACCESS_TOKEN__START';
export const SET_ACCESS_TOKEN__ERROR = 'SET_ACCESS_TOKEN__ERROR';

// dashboard actions
export const SELECT_LEVEL = 'SELECT_LEVEL';
export const SELECT_SESSION = 'SELECT_SESSION';

// device actions
export const DEVICE_CONNECT = 'DEVICE_CONNECT';
export const DEVICE_CONNECT__START = 'DEVICE_CONNECT__START';
export const DEVICE_CONNECT__ERROR = 'DEVICE_CONNECT__ERROR';
export const DEVICE_CONNECT_STATUS = 'DEVICE_CONNECT_STATUS';
export const DEVICE_CONNECT_STATUS__START = 'DEVICE_CONNECT_STATUS__START';
export const DEVICE_CONNECT_STATUS__ERROR = 'DEVICE_CONNECT_STATUS__ERROR';
export const DEVICE_DISCONNECT = 'DEVICE_DISCONNECT';
export const DEVICE_DISCONNECT__START = 'DEVICE_DISCONNECT__START';
export const DEVICE_DISCONNECT__ERROR = 'DEVICE_DISCONNECT__ERROR';
export const DEVICE_FORGET = 'DEVICE_FORGET';
export const DEVICE_FORGET__START = 'DEVICE_FORGET__START';
export const DEVICE_FORGET__ERROR = 'DEVICE_FORGET__ERROR';
export const DEVICE_GET_INFO = 'DEVICE_GET_INFO';
export const DEVICE_GET_INFO__START = 'DEVICE_GET_INFO__START';
export const DEVICE_GET_INFO__ERROR = 'DEVICE_GET_INFO__ERROR';
export const DEVICE_SELF_TEST_REQUESTED = 'DEVICE_SELF_TEST_REQUESTED';
export const DEVICE_SELF_TEST_UPDATED = 'DEVICE_SELF_TEST_UPDATED';
export const DEVICE_RESTORE_SAVED_SESSION = 'DEVICE_RESTORE_SAVED_SESSION';
export const DEVICE_CLEAR_SAVED_SESSION = 'DEVICE_CLEAR_SAVED_SESSION';
export const DEVICE_FIRMWARE_UPDATE_STARTED = 'DEVICE_FIRMWARE_UPDATE_STARTED';
export const DEVICE_FIRMWARE_UPDATE_ENDED = 'DEVICE_FIRMWARE_UPDATE_ENDED';
export const DEVICE_SET_PENDING_UPDATE = 'DEVICE_SET_PENDING_UPDATE';
export const DEVICE_UNSET_PENDING_UPDATE = 'DEVICE_UNSET_PENDING_UPDATE';

// posture actions
export const SET_SESSION_TIME = 'SET_SESSION_TIME';
export const SET_SESSION_TIME__START = 'SET_SESSION_TIME__START';
export const SET_SESSION_TIME__ERROR = 'SET_SESSION_TIME__ERROR';

// support actions
export const UPDATE_SUPPORT_MESSAGE = 'UPDATE_SUPPORT_MESSAGE';
export const CREATE_SUPPORT_TICKET = 'CREATE_SUPPORT_TICKET';
export const CREATE_SUPPORT_TICKET__START = 'CREATE_SUPPORT_TICKET__START';
export const CREATE_SUPPORT_TICKET__ERROR = 'CREATE_SUPPORT_TICKET__ERROR';

// user actions
export const FETCH_USER = 'FETCH_USER';
export const FETCH_USER__START = 'FETCH_USER__START';
export const FETCH_USER__ERROR = 'FETCH_USER__ERROR';
export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_USER__START = 'UPDATE_USER__START';
export const UPDATE_USER__ERROR = 'UPDATE_USER__ERROR';
export const UPDATE_USER_SETTINGS = 'UPDATE_USER_SETTINGS';
export const UPDATE_USER_SETTINGS__START = 'UPDATE_USER_SETTINGS__START';
export const UPDATE_USER_SETTINGS__ERROR = 'UPDATE_USER_SETTINGS__ERROR';
export const FETCH_USER_SESSIONS = 'FETCH_USER_SESSIONS';
export const FETCH_USER_SESSIONS__START = 'FETCH_USER_SESSIONS__START';
export const FETCH_USER_SESSIONS__ERROR = 'FETCH_USER_SESSIONS__ERROR';
export const PREPARE_USER_UPDATE = 'PREPARE_USER_UPDATE';
export const PREPARE_USER_UPDATE__START = 'PREPARE_USER_UPDATE__START';
export const PREPARE_USER_UPDATE__ERROR = 'PREPARE_USER_UPDATE__ERROR';
export const FETCH_USER_WORKOUTS = 'FETCH_USER_WORKOUTS';
export const FETCH_USER_WORKOUTS__START = 'FETCH_USER_WORKOUTS__START';
export const FETCH_USER_WORKOUTS__ERROR = 'FETCH_USER_WORKOUTS__ERROR';
