# Uncomment this line if you're using Swift or would like to use dynamic frameworks
# use_frameworks!

# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

target 'backbone' do

  # Pods for backbone
  pod 'Metawear-iOSAPI'

  target 'backboneTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
