# Uncomment this line if you're using Swift or would like to use dynamic frameworks
# use_frameworks!

# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

target 'Backbone' do

  # Pods for Backbone
  pod 'Mixpanel'
  pod 'AWSCognito'
  pod 'AWSKinesis'

  target 'BackboneTests' do
    inherit! :search_paths
    # Pods for BackboneTests
  end

end
